accounts/urls.py
from django.urls import path, include
from . import views


app_name = 'account'

urlpatterns = [
    path('', views.profile_complete, name='profile_complete'),
    path('auth/', include('django.contrib.auth.urls')),
    # register path is archived since we're using allauth'
    # path('register/', views.register, name='register'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('groups/', views.GroupListView.as_view(), name='groups'),
    path('user-requests/', views.user_requests_list, name='user_requests'),
    path('permission-error/', views.permission_error, name='permission_error'),
    path('approval/<int:pk>/<int:approved>',
         views.user_approval, name='user_approval'),
    path('modify-and-approve/<int:pk>/',
        views.user_approval_with_modification,
        name='approval_with_modification'
    ),
    path('user/<int:pk>/change', views.UserUpdateView.as_view(), name='user_change'),
    path('api/upload-profile-picture', views.profile_picture_upload,
        name='profile_picture_upload'
    ),
]

articles/urls.py
from django.urls import path

from . import views
from .dashboard_views import dashboard_views

app_name = 'articles'

urlpatterns = [
    path('',
        views.ArticleList.as_view(),
        name='home'
    ),
    path('all/', 
        views.AllArticles.as_view(), 
        name='all_articles'
    ),
    path('manage/', dashboard_views.dashboard_manage_article,
        name='dashboard_manage'
    ),
    path('manage/subscribers/', 
        dashboard_views.SubscribersManageView.as_view(),
        name='subscribers'
    ),
    path('dashboard/delete/<int:pk>/', 
        dashboard_views.dashboard_article_delete, 
        name='dashboard_article_delete'
    ),
    path('dashboard/new/',
         dashboard_views.dashboard_article_publish,
        name='dashboard_article_publish'
    ),
    path('dashboard/draft/<int:pk>/', 
        dashboard_views.dashboard_article_draft,
        name='dashboard_article_draft'
    ),
    path('dashboard/publish/article/',
         views.ArticleCreateFromDashboard.as_view(),
        name='publish_article_from_dashboard'
    ),
    path('new/',
        views.ArticleCreate.as_view(),
        name='create'
    ),
    path('newsletter/',
        views.newsletter,
        name='newsletter'
    ),
    path('author/<str:slug>/',
        views.AuthorProfile.as_view(),
        name='author_profile'
    ),
    path('<slug:slug>/update/',
        views.ArticleUpdate.as_view(),
        name='update'
    ),
    path('<slug:slug>/like/',
        views.ArticleLike.as_view(),
        name='like'
    ),
    path('<slug:slug>/',
        views.ArticleDetail.as_view(),
        name='detail'
    ),
    path('<slug:slug>/articles/',
        views.CategoryArticles.as_view(),
        name='category_articles'
    ),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

from institute.models import InstituteProfile
from accounts.views import dashboard

try:
    institute = InstituteProfile.objects.get(active=True)
    admin.site.site_header = institute.site_header
    admin.site.site_title = institute.site_title
    admin.site.index_title = institute.index_title
except:
    admin.site.site_header = 'Django Administration'
    admin.site.site_title = 'Django Site Admin'
    admin.site.index_title = 'Django Administration'

DJANGO_ADMIN_URL = settings.DJANGO_ADMIN_URL + '/'
urlpatterns = [
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path(DJANGO_ADMIN_URL, admin.site.urls),
    path('', include('pages.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('dashboard/', dashboard, name='index_view'),
    path('accounts/', include('allauth.urls')),
    path('blog/', include('articles.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('account/', include('accounts.urls')),
    path('academics/', include('academics.urls')),
    path('notices/', include('notices.site_urls')),
    path('notices/dashboard/', include('notices.dashboard_urls')),
    path('students/', include('students.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('teachers/', include('teachers.urls')),
    path('result/', include('result.urls')),
    path('institute/', include('institute.urls')),
    path(
        'password-reset/',
        auth_views.PasswordResetView.as_view(
            template_name='account/password/password_reset.html'
        ),
        name="password_reset",
    ),
    path(
        'password_reset/done/',
        auth_views.PasswordResetDoneView.as_view(
            template_name='account/password/password_reset_done.html'
        ),
        name="password_reset_done",
    ),
    path(
        'password-reset-confirm/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='account/password/password_reset_confirm.html'
        ),
        name='password_reset_confirm',
    ),
    path(
        'password-reset-complete/',
        auth_views.PasswordResetCompleteView.as_view(
            template_name='account/password/password-reset-complete.html'
        ),
        name='password_reset_complete'
    ),
    path('dashboard/payments/', include('payments.urls')),
    # API URLS
    path('api/', include('articles.api.routes')),
    path('upload/', include('django_file_form.urls')),
]

urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)
urlpatterns += static(
    settings.STATIC_URL,
    document_root=settings.STATIC_ROOT
)

if "debug_toolbar" in settings.INSTALLED_APPS:
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls))
    ] + urlpatterns

pages/urls.py
from django.urls import path
from pages.payment_views.sslpay import online_admission_sslpayment
from . import views

app_name = 'pages'
urlpatterns = [
     path('', views.index, name='landing'),
     path('admission/', views.online_admission, name='online_admission'),
     path('admission/payment/<int:pk>/', views.online_admission_payment,
          name='online_admission_payment'
     ),
     path('admission/sslpayment/<int:pk>/', online_admission_sslpayment,
          name='online_admission_sslpayment'
     ),
     path('admission/paynow/<int:pk>/', views.payment,
          name='payment'
     ),
     path('userguide/', views.user_guide_view,
          name='userguide'
     ),
]

templates/website/partials/tailwind_base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Notices | {{ request_institute }}</title>
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet" />
</head>

<body>
    {% include 'website/partials/tailwind_navbar.html' %}

    {% block content %}
    {% endblock content %}
</body>
</html>

templates/website/partials/tailwind_navbar.html
{% load static %}

<!-- This example requires Tailwind CSS v2.0+ -->
<nav class="bg-gray-800">
    <div class="max-w-7xl mx-auto px-2 sm:px-6 lg:px-8">
        <div class="relative flex items-center justify-between h-16">
            <div class="absolute inset-y-0 left-0 flex items-center sm:hidden">
                <!-- Mobile menu button-->
                <button type="button"
                    class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-white hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white"
                    aria-controls="mobile-menu" aria-expanded="false">
                    <span class="sr-only">Open main menu</span>
                    <!--
            Icon when menu is closed.

            Heroicon name: outline/menu

            Menu open: "hidden", Menu closed: "block"
          -->
                    <svg class="block h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                        stroke="currentColor" aria-hidden="true">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                            d="M4 6h16M4 12h16M4 18h16" />
                    </svg>
                    <!--
            Icon when menu is open.

            Heroicon name: outline/x

            Menu open: "block", Menu closed: "hidden"
          -->
                    <svg class="hidden h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                        stroke="currentColor" aria-hidden="true">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                            d="M6 18L18 6M6 6l12 12" />
                    </svg>
                </button>
            </div>
            <div class="flex-1 flex items-center justify-center sm:items-stretch sm:justify-start">
                <div class="flex-shrink-0 flex items-center">
                    <img class="block lg:hidden h-8 w-auto"
                        src="{% if request_institute.logo %}{{ request_institute.logo.url }}{% else %}{% static 'landing/img/footer-logo.png' %}{% endif %}"
                        alt="Workflow">
                    <img class="hidden lg:block h-8 w-auto"
                        src="{% if request_institute.logo %}{{ request_institute.logo.url }}{% else %}{% static 'landing/img/footer-logo.png' %}{% endif %}"
                        alt="Workflow">
                </div>
                <div class="hidden sm:block sm:ml-6">
                    <div class="flex space-x-4">
                        <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
                        <a href="/" class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium" aria-current="page">
                            Home
                        </a>

                        <a href="{% url 'notices:notices' %}"
                            class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium">
                            Notices
                        </a>

                        <a href="{% url 'articles:home' %}"
                            class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium">
                            Blog
                        </a>
                    </div>
                </div>
            </div>

            <!-- RIGH SIDE -->
            <div class="absolute inset-y-0 right-0 flex items-center pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0">

                {% if user.is_authenticated %}
                    {% if user.approval_status == 'a' %}
                        <a href="{% url 'account:dashboard' %}" class="bg-gray-900 text-gray-300 hover:bg-gray-700 
                                        hover:text-white px-3 py-2 rounded-md text-sm font-medium">
                            Dashboard
                        </a>
                        <a href="{% url 'account:profile_complete' %}" class="text-gray-300 hover:bg-gray-700 
                            hover:text-white px-3 py-2 rounded-md text-sm font-medium">
                            Profile
                        </a>
                        <a href="{% url 'account_logout' %}" class="text-gray-300 hover:bg-gray-700 
                                        hover:text-white px-3 py-2 rounded-md text-sm font-medium">
                            Logout
                        </a>
                    {% else %}
                    <a href="{% url 'account:profile_complete' %}" class="text-gray-300 hover:bg-gray-700 
                                    hover:text-white px-3 py-2 rounded-md text-sm font-medium">
                        Verify Your Profile
                    </a>
                    {% endif %}
                {% else %}
                <a href="{% url 'account_login' %}" class="bg-gray-900 text-gray-300 mr-3 hover:bg-gray-700 
                            hover:text-white px-3 py-2 rounded-md text-sm font-medium">
                    Login
                </a>
                <a href="{% url 'account_signup' %}" class="bg-blue-800 text-gray-300 hover:bg-gray-700 
                            hover:text-white px-3 py-2 rounded-md text-sm font-medium">
                    Create Account
                </a>
                {% endif %}
            </div>
        </div>
    </div>

    <!-- Mobile menu, show/hide based on menu state. -->
    <div class="sm:hidden" id="mobile-menu">
        <div class="px-2 pt-2 pb-3 space-y-1">
            <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
            <a href="#" class="bg-gray-900 text-white block px-3 py-2 rounded-md text-base font-medium"
                aria-current="page">Dashboard</a>

            <a href="#"
                class="text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium">Team</a>

            <a href="#"
                class="text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium">Projects</a>

            <a href="#"
                class="text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium">Calendar</a>
        </div>
    </div>
</nav>

templates/website/partials/website_base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="keywords" content="Bootstrap, Landing page, Template, Business, Service">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="author" content="Grayrids">
    <title>{{ request_institute.site_title }}</title>
    <!--====== Favicon Icon ======-->
    <link rel="shortcut icon" 
      href="{{ request_institute.favicon.url }}" 
      type="image/png">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'landing/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'landing/css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'landing/css/LineIcons.css' %}">
    <link rel="stylesheet" href="{% static 'landing/css/owl.carousel.css' %}">
    <link rel="stylesheet" href="{% static 'landing/css/owl.theme.css' %}">
    <link rel="stylesheet" href="{% static 'landing/css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'landing/css/nivo-lightbox.css' %}">
    <link rel="stylesheet" href="{% static 'landing/css/main.css' %}">
    <link rel="stylesheet" href="{% static 'landing/css/responsive.css' %}">
    <!-- FONTAWESOME CDN -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.2/css/all.css" integrity="sha384-vSIIfh2YWi9wW0r9iZe7RJPrKwp6bG+s9QZMoITbCckVJqGCCRhc+ccxNcdpHuYu" crossorigin="anonymous">

    {% block extra_css %}{% endblock %}

  </head>

  <body>

  {% block main_content %}

  {% endblock %}


    <!-- Footer Section Start -->
    {% comment %}
    <footer>
      <!-- Footer Area Start -->
      <section id="footer-Content">
        <div class="container">
          <!-- Start Row -->
          <div class="row">

          <!-- Start Col -->
            <div class="col-lg-3 col-md-6 col-sm-6 col-xs-6 col-mb-12">

              <div class="footer-logo">
               <img 
               src="{% if request_institute.logo %}{{ request_institute.logo.url }}{% else %}{% static 'landing/img/footer-logo.png' %}{% endif %}" 
               alt="{{ request_institute.name }}">
              </div>
            </div>
             <!-- End Col -->
              <!-- Start Col -->
            <div class="col-lg-2 col-md-6 col-sm-6 col-xs-6 col-mb-12">
              <div class="widget">
                <h3 class="block-title">Company</h3>
                <ul class="menu">
                  <li><a href="#">  - About Us</a></li>
                  <li><a href="#">- Career</a></li>
                  <li><a href="#">- Blog</a></li>
                  <li><a href="#">- Press</a></li>
                </ul>
              </div>
            </div>
             <!-- End Col -->
              <!-- Start Col -->
            <div class="col-lg-2 col-md-6 col-sm-6 col-xs-6 col-mb-12">
              <div class="widget">
                <h3 class="block-title">Product</h3>
                <ul class="menu">
                  <li><a href="#">  - Customer Service</a></li>
                  <li><a href="#">- Enterprise</a></li>
                  <li><a href="#">- Price</a></li>
                  <li><a href="#">- Scurity</a></li>
                  <li><a href="#">- Why SLICK?</a></li>
                </ul>
              </div>
            </div>
             <!-- End Col -->
              <!-- Start Col -->
            <div class="col-lg-2 col-md-6 col-sm-6 col-xs-6 col-mb-12">
              <div class="widget">
                <h3 class="block-title">Download App</h3>
                <ul class="menu">
                  <li><a href="#">  - Android App</a></li>
                  <li><a href="#">- IOS App</a></li>
                  <li><a href="#">- Windows App</a></li>
                  <li><a href="#">- Play Store</a></li>
                  <li><a href="#">- IOS Store</a></li>
                </ul>
              </div>
            </div>
             <!-- End Col -->
              <!-- Start Col -->
            <div class="col-lg-3 col-md-6 col-sm-6 col-xs-6 col-mb-12">
              <div class="widget">
                <h3 class="block-title">Subscribe Now</h3>
                <p>
                  Get updates from us by subscribing to our mailing list.
                </p>
                <div class="subscribe-area">
                  <form action="{% url 'articles:newsletter'%}" method="post">
                    <input type="email" name="email" class="form-control" placeholder="Enter Email">
                    <span id="subscribe-form-submit">
                      <button type="submit">
                        <i class="lni-chevron-right"></i>
                      </button>
                    </span>
                  </form>
                </div>
              </div>
            </div>
            <!-- End Col -->
          </div>
          <!-- End Row -->
        </div>
        <!-- Copyright Start  -->

        <!-- <div class="copyright">
          <div class="container">
            <div class="row">
              <div class="col-md-12">
                <div class="site-info text-center">
                  <p>Crafted by <a href="http://uideck.com" rel="nofollow">UIdeck</a></p>
                </div>

              </div>
            </div>
          </div>
        </div> -->
      <!-- Copyright End -->
      </section>
      <!-- Footer area End -->

    </footer>
    {% endcomment %}
    <!-- Footer Section End -->


    <!-- Go To Top Link -->
    <a href="#" class="back-to-top">
      <i class="lni-chevron-up"></i>
    </a>

    <!-- Preloader -->
    <div id="preloader">
      <div class="loader" id="loader-1"></div>
    </div>
    <!-- End Preloader -->

    <!-- jQuery first, then Tether, then Bootstrap JS. -->
    <script src="{% static 'landing/js/jquery-min.js' %}"></script>
    <script src="{% static 'landing/js/popper.min.js' %}"></script>
    <script src="{% static 'landing/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'landing/js/owl.carousel.js' %}"></script>
    <script src="{% static 'landing/js/jquery.nav.js' %}"></script>
    <script src="{% static 'landing/js/scrolling-nav.js' %}"></script>
    <script src="{% static 'landing/js/jquery.easing.min.js' %}"></script>
    <script src="{% static 'landing/js/nivo-lightbox.js' %}"></script>
    <script src="{% static 'landing/js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'landing/js/main.js' %}"></script>
    {% block extra_js %}{% endblock %}

  </body>
</html>

templates/website/partials/website_navbar.html
{% load static %}

<nav class="navbar navbar-expand-md fixed-top scrolling-navbar">
    <div class="container">
          <a href="/" class="navbar-brand">
            <img src="{% if request_institute.logo %}{{ request_institute.logo.url }}{% else %}{% static 'landing/img/footer-logo.png' %}{% endif %}"
              alt="{{ request_institute.name }}"
              height="60">
            </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <i class="lni-menu"></i>
          </button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto w-100 justify-content-end">
              <li class="nav-item">
                <a class="nav-link page-scroll" href="/">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link page-scroll" href="{% url 'notices:notices' %}">
                  Notices
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link page-scroll" href="{% url 'articles:home' %}">Blog</a>
              </li>
              {% if request.user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link page-scroll" href="{% url 'account:profile_complete' %}">My Account</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link page-scroll" href="{% url 'account_logout' %}">
                    Logout
                  </a>
                </li>
	            {% else %}
	            <li class="nav-item">
                  <a class="nav-link page-scroll" href="{% url 'account_login' %}">
                    signIn/SignUp
                  </a>
              </li>
              {% endif %}
              <li class="nav-item">
                <a class="btn btn-singin" href="{% url 'account:dashboard' %}">Dashboard</a>
              </li>
            </ul>
          </div>
    </div>
</nav>