config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

from institute.models import InstituteProfile
from accounts.views import dashboard

try:
    institute = InstituteProfile.objects.get(active=True)
    admin.site.site_header = institute.site_header
    admin.site.site_title = institute.site_title
    admin.site.index_title = institute.index_title
except:
    admin.site.site_header = 'Django Administration'
    admin.site.site_title = 'Django Site Admin'
    admin.site.index_title = 'Django Administration'

DJANGO_ADMIN_URL = settings.DJANGO_ADMIN_URL + '/'
urlpatterns = [
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path(DJANGO_ADMIN_URL, admin.site.urls),
    path('', include('pages.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('dashboard/', dashboard, name='index_view'),
    path('accounts/', include('allauth.urls')),
    path('blog/', include('articles.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('account/', include('accounts.urls')),
    path('academics/', include('academics.urls')),
    path('notices/', include('notices.site_urls')),
    path('notices/dashboard/', include('notices.dashboard_urls')),
    path('students/', include('students.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('teachers/', include('teachers.urls')),
    path('result/', include('result.urls')),
    path('institute/', include('institute.urls')),
    path(
        'password-reset/',
        auth_views.PasswordResetView.as_view(
            template_name='account/password/password_reset.html'
        ),
        name="password_reset",
    ),
    path(
        'password_reset/done/',
        auth_views.PasswordResetDoneView.as_view(
            template_name='account/password/password_reset_done.html'
        ),
        name="password_reset_done",
    ),
    path(
        'password-reset-confirm/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='account/password/password_reset_confirm.html'
        ),
        name='password_reset_confirm',
    ),
    path(
        'password-reset-complete/',
        auth_views.PasswordResetCompleteView.as_view(
            template_name='account/password/password-reset-complete.html'
        ),
        name='password_reset_complete'
    ),
    path('dashboard/payments/', include('payments.urls')),
    # API URLS
    path('api/', include('articles.api.routes')),
    path('upload/', include('django_file_form.urls')),
]

urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)
urlpatterns += static(
    settings.STATIC_URL,
    document_root=settings.STATIC_ROOT
)

if "debug_toolbar" in settings.INSTALLED_APPS:
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls))
    ] + urlpatterns

pages/urls.py
from django.urls import path
from pages.payment_views.sslpay import online_admission_sslpayment
from . import views

app_name = 'pages'
urlpatterns = [
     path('', views.index, name='landing'),
     path('admission/', views.online_admission, name='online_admission'),
     path('admission/payment/<int:pk>/', views.online_admission_payment,
          name='online_admission_payment'
     ),
     path('admission/sslpayment/<int:pk>/', online_admission_sslpayment,
          name='online_admission_sslpayment'
     ),
     path('admission/paynow/<int:pk>/', views.payment,
          name='payment'
     ),
     path('userguide/', views.user_guide_view,
          name='userguide'
     ),
]

result/urls.py
from django.urls import path

from . import views

app_name = 'result'

urlpatterns = [
    path('', views.result_view, name='result_home'),
    path('create-subject-group/', views.create_subject_group,
        name='create_subject_group'
    ),
    path('subject-groups/', views.subject_group_list, name='subject_groups'),
    path('student/<int:student_pk>/', views.result_detail_view,
        name='result_detail_view'
    ),
    path('entry/', views.result_entry,
        name='result_entry'
    ),
    path('student/find/<str:student_id>', views.find_student,
        name='find_student'
    ),
]

students/urls.py
from datetime import datetime

from django.urls import path, register_converter

from .views import students_views as views
from .views import pdf_views
from .views import report_views

app_name = 'students'


class DateConverter:
     # Convert a string passed as date in datetime object
     regex = '\d{4}-\d{2}-\d{2}'

     def to_python(self, value):
          return datetime.strptime(value, '%Y-%m-%d')
     
     def to_url(self, value):
          return value

register_converter(DateConverter, 'date')

urlpatterns = [
     path('', views.students_dashboard_index, 
          name='students_dashboard_index'),
     # TEST PDF PRINTER
     path('pdf/', pdf_views.test_pdf, name='test_pdf'),
     path('add/', views.add_student_view, name='add_student'),
     path('all/', views.students_view, name='all_student'),
     path('alumnus/', views.AlumnusListView.as_view(), name='alumnus'),
     path('applicants/', views.all_applicants, name='all_applicants'),
     path('applicants/unpaid/', views.unpaid_registrants, name='unpaid_registrants'),
     path('applicants/unpaid/mark-paid/', views.mark_as_paid_or_unpaid,
          name='mark_as_paid_or_unpaid'),
     path('add-counsel-data/<int:student_id>/', views.add_counseling_data, 
          name='add_counseling_data'),
     path('admitted-students/', views.admitted_students_list,
          name='admitted_student_list'),
     path('admission-confirm/', views.admission_confirmation,
          name='admission_confirmation'),
     path('api/batches/<int:department_code>/', views.get_json_batch_data,
          name='get_json_batch_data'),
     path('api/yearly-graph/', report_views.yearly_graph_api,
          name='yearly_graph_api'),
     path('online-applicants/<int:pk>/admit/', views.admit_student,
          name='admit_student'),
     path('paid-registrants/', views.paid_registrants, 
          name='paid_registrants'),
     path('rejected-registrants/', views.rejected_registrants,
          name='rejected_registrants'),
     path('update-registrant/<int:pk>/', views.update_online_registrant, 
          name='update_online_registrant'),
     path('update/<int:pk>/', views.StudentUpdateView.as_view(),
          name='update_student'),
     path('<int:pk>/detail/', views.StudentDetailsView.as_view(),
          name='student_details'),
     path('<int:pk>/delete/', views.student_delete_view, name='delete_student'),
     path('<int:pk>/students/', views.students_by_department_view,
          name='students_by_dept'),
     path('counsel-report/', report_views.counsel_monthly_report, name='counsel_monthly_report'),
     path('counsel-report/<str:response_type>/', report_views.counsel_monthly_report,
          name='counsel_monthly_report_typed'),
     path('counsel-report/<str:response_type>/<date:date_param>/',
          report_views.counsel_monthly_report,
          name='counsel_report_monthly_with_date'),
]

students/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.bootstrap import Tab, TabHolder
from crispy_forms.layout import (
    Layout, Field, ButtonHolder, Submit
)
from .models import AdmissionStudent, CounselingComment, Student


class StudentForm(forms.ModelForm):
    class Meta:
        model = AdmissionStudent
        fields = [
            'name',
            'fathers_name',
            'mothers_name',
            'date_of_birth',
            'city',
            'current_address',
            'permanent_address',
            'mobile_number',
            'guardian_mobile_number',
            'email',
            'tribal_status',
            'children_of_freedom_fighter',
            'department_choice',
            'exam_name',
            'passing_year',
            'group',
            'board',
            'ssc_roll',
            'ssc_registration',
            'gpa',
            'photo',
            'marksheet_image',
            'admission_policy_agreement',
        ]
        widgets = {
            'date_of_birth': forms.TextInput({'type': 'date'}),
        }


class AdmissionForm(forms.ModelForm):
    class Meta:
        model = AdmissionStudent
        fields = [
            'choosen_department',
        ]


class StudentRegistrantUpdateForm(forms.ModelForm):
    class Meta:
        model = AdmissionStudent
        fields = [
            'name',
            'photo',
            'fathers_name',
            'mothers_name',
            'date_of_birth',
            'current_address',
            'permanent_address',
            'mobile_number',
            'email',
            'choosen_department',
            'admitted',
            'paid',
            'rejected',
        ]
        widgets = {
            'date_of_birth': forms.TextInput({'type': 'date'}),
        }


class CounselingDataForm(forms.ModelForm):
    class Meta:
        model = CounselingComment
        fields = ['comment', ]


class StudentUpdateForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = (
            'roll',
            'registration_number',
            'semester',
            'guardian_mobile',
            'is_alumni', 'is_dropped'
        )

result/views.py
from django.db import IntegrityError
from django.contrib import messages
from django.contrib.auth.decorators import user_passes_test
from django.shortcuts import render, get_object_or_404, redirect
from django.http import JsonResponse, HttpResponse

from students.models import Student
from academics.models import Semester, Subject, Department
from .models import Result, SubjectGroup
from .filters import ResultFilter, SubjectGroupFilter
from permission_handlers.basic import user_is_verified
from permission_handlers.administrative import user_is_teacher_or_administrative


@user_passes_test(user_is_verified)
def result_view(request):
    if not request.GET:
        qs = Result.objects.none()
    else:
        qs = Result.objects.all()
    f = ResultFilter(request.GET, queryset=qs)
    ctx = {'filter': f, }
    return render(request, 'result/result_filter.html', ctx)


@user_passes_test(user_is_verified)
def result_detail_view(request, student_pk):
    student = get_object_or_404(Student, pk=student_pk)
    student_results = student.results.all()
    semesters = list(Semester.objects.all())
    semester_results = {}
    active_semesters = []

    for semester in semesters:
        results = student_results.filter(semester=semester)
        if results:
            active_semesters.append(semester)
            semester_results.update(
                {f'{semester}': results}
            )
    ctx = {
        'student': student,
        'semester_results': semester_results,
        'active_semesters': active_semesters
    }
    return render(request, 'result/result_detail.html', ctx)


def find_student(request, student_id):
    """ Find student by given id for result entry."""
    student = Student.objects.get(
        temporary_id=student_id
    )
    ctx = {
        'student_name': student.admission_student.name,
        'student_batch': student.batch.number,
        'image_url': student.admission_student.photo.url
    }
    return JsonResponse({'data': ctx})


@user_passes_test(user_is_teacher_or_administrative)
def result_entry(request):
    if not request.GET:
        qs = SubjectGroup.objects.none()
    else:
        qs = SubjectGroup.objects.all()

    subject_group_filter = SubjectGroupFilter(
        request.GET,
        queryset=qs
    )

    if request.method == 'POST':
        data_items = request.POST.items()
        # get student from pk
        student_temp_id = request.POST.get('student_id')
        student = Student.objects.get(temporary_id=student_temp_id)
        semester = Semester.objects.get(pk=int(request.POST.get('semester')))

        result_created = {}
        for key, value in data_items:
            # get subject from pk
            if '.' in key:
                try:
                    s_pk = int(key.split('.')[1])
                    subject = Subject.objects.get(pk=s_pk)
                    if not result_created.get(str(s_pk)):
                        # get subject marks
                        practical_marks = int(
                            request.POST.get(f'practical_marks.{s_pk}')
                        )
                        theory_marks = int(
                            request.POST.get(f'theory_marks.{s_pk}')
                        )
                        result = Result(
                            student=student,
                            semester=semester,
                            subject=subject,
                            practical_marks=practical_marks,
                            theory_marks=theory_marks
                        )
                        try:
                            result.save()
                            result_created[str(s_pk)] = True
                        except IntegrityError:
                            messages.error(
                                request,
                                f'{student.admission_student.name}\'s result '
                                f'for {subject} has been created already.'
                            )
                except ValueError:
                    pass
        return redirect('result:result_entry')
    ctx = {
        'subject_group_filter': subject_group_filter,
    }
    return render(request, 'result/result_entry.html', ctx)


@user_passes_test(user_is_teacher_or_administrative)
def create_subject_group(request):
    departments = Department.objects.all()
    semesters = Semester.objects.all()
    subjects = Subject.objects.all()

    if request.method == 'POST':
        dept_pk = int(request.POST.get('department'))
        subject_list = request.POST.getlist('subject')
        semester_pk = int(request.POST.get('semester'))

        dept = Department.objects.get(pk=dept_pk)
        semester = Semester.objects.get(pk=semester_pk)

        subject_group = SubjectGroup.objects.create(
            department=dept,
            semester=semester
        )

        subject_objects = []
        for s_pk in subject_list:
            subj = Subject.objects.get(pk=int(s_pk))
            subject_objects.append(subj)
            subject_group.subjects.add(subj)

        subject_group.save()
        return redirect('result:subject_groups')
    ctx = {
        'departments': departments,
        'semesters': semesters,
        'subjects': subjects,
    }
    return render(request, 'result/create_subject_groups.html', ctx)


@user_passes_test(user_is_verified)
def subject_group_list(request):
    subject_groups = SubjectGroup.objects.all()
    ctx = {
        'subject_groups': subject_groups,
    }
    return render(request, 'result/subject_group_list.html', ctx)

students/views/pdf_views.py
import io

from reportlab.pdfgen import canvas

from django.http import FileResponse



def test_pdf(request):
    # create file like buffer to recieve PDF data
    buffer = io.BytesIO()
    # create pdf using buffer file as pdf
    p = canvas.Canvas(buffer)
    # Draw things on the PDF. Here's where the PDF generation happens.
    # See the ReportLab documentation for the full list of functionality.
    p.drawString(100, 100, "Hello world.")

    # Close the PDF object cleanly, and we're done.
    p.showPage()
    p.save()

    # FileResponse sets the Content-Disposition header so that browsers
    # present the option to save the file.
    buffer.seek(0)

    return FileResponse(buffer, filename='test_pdf.pdf')

students/templates/students/all_applicants.html
{% extends 'dashboard.html' %}
{% load static %}

{% block dashboard-body %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="#">Dashboard</a></li>
        <li class="breadcrumb-item">
            <a href="{% url 'students:students_dashboard_index' %}">Applicants</a>
        </li>
        <li class="breadcrumb-item active" aria-current="page">All</li>
    </ol>
</nav>

<div class="row">
    <div class="col-12 mb-2">
        <h4 class="ml-0 mb-1">All Applicants</h4>
        <small class="mb-3">
          Click on any student info to update any details.
        </small>
    </div>
  <div class="col-12">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th scope="col">SYL</th>
          <th scope="col">Name</th>
          <th scope="col">Application Date</th>
          <th scope="col">Payment Status</th>
          <th scope="col">Admitted</th>
          <th scope="col">Contact</th>
        </tr>
      </thead>
      <tbody>
        {% for applicant in registrants %}
        <tr>
          <th scope="row">
            <a href="{% url 'students:update_online_registrant' pk=applicant.id %}">
              {{ forloop.counter }}
            </a>
          </th>
          <td>
            <a href="{% url 'students:update_online_registrant' pk=applicant.id %}">
              {{ applicant.name }}
            </a>
          </td>
          <td>
            <a href="{% url 'students:update_online_registrant' pk=applicant.id %}">
              {{ applicant.created }}
            </a>
          </td>
          <td style="text-align: center;">
            <a href="{% url 'students:update_online_registrant' pk=applicant.id %}">
              {% if applicant.paid %}
                <img src="{% static 'images/checked.png' %}" width="16" alt="">
              {% else %}
                <img src="{% static 'images/cross.png' %}" width="16" alt="">
              {% endif %}
            </a>
          </td>
          <td style="text-align: center;">
              <a href="{% url 'students:update_online_registrant' pk=applicant.id %}">
                  {% if applicant.admitted %}
                    <img src="{% static 'images/checked.png' %}" width="16" alt="">
                  {% else %}
                    <img src="{% static 'images/cross.png' %}" width="16" alt="">
                  {% endif %}
              </a>
          </td>
          <td>
              <a href="{% url 'students:update_online_registrant' pk=applicant.id %}">
                  {{ applicant.mobile_number }}
              </a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

{% endblock %}


{% block extrajs %}
  <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
{% endblock %}

students/templates/students/dashboard_all_cleared_students.html
{% extends 'dashboard.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block extra_header %}
{% endblock %}

{% block dashboard-body %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="#">Dashboard</a></li>
        <li class="breadcrumb-item">
            <a href="{% url 'students:students_dashboard_index' %}">Applicants</a>
        </li>
        <li class="breadcrumb-item active" aria-current="page">Admitted Applicants</li>
    </ol>
</nav>

<!-- Online students Table Row -->
<div class="container-fluid">
    <div class="row">
        <div class="col-12 pl-0">
            <h4 class="ml-0 mb-1">Paid & Cleared Applicants</h4>
            <small class="mb-3">
                Applicants who are approved to be admitted and cleared their admission fees.
            </small>
        </div>
        <!-- Admitted Students Table -->
        <div id="admitted-students" class="col-md-12 mt-4">
            <table class="table table-bordered table-hover">
                <thead class="thead-light">
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Image</th>
                        <th scope="col">Name</th>
                        <th scope="col">Address</th>
                        <th scope="col">Department</th>
                        <th scope="col">Admission Date</th>
                        <th scope="col">Actions</th>
                    </tr>
                </thead>
                <tbody class="bg-light">
                
                    {% for applicant in admitted_students %}
                    <tr>
                        <th scope="row">{{ applicant.id }}</th>
                        <td>
                            <img src="{{ applicant.photo.url }}" width="50" height="50">
                        </td>
                        <td>{{ applicant.name }}</td>
                        <td>{{ applicant.permanent_address }}</td>
                        <td>{{ applicant.choosen_department }}</td>
                        <td>{{ applicant.admission_date }}</td>
                        <td>
                            <a href="{% url 'students:update_online_registrant' pk=applicant.id %}" class="btn btn-sm btn-success">
                                Update
                            </a>
                        </td>
                    </tr>
                    {% endfor %}
                    
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

{% block extrajs %}
    <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
{% endblock %}

students/templates/students/dashboard_paid_students.html
{% extends 'dashboard.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block extra_header %}
{% endblock %}

{% block dashboard-body %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="#">Dashboard</a></li>
        <li class="breadcrumb-item">
            <a href="{% url 'students:students_dashboard_index' %}">Students</a>
        </li>
        <li class="breadcrumb-item active" aria-current="page">Paid Applicants</li>
    </ol>
</nav>

<!-- Online Applicants Table Row -->
<div class="container-fluid">
    <div class="row">
        <div class="col-12 pl-0">
            <h4 class="ml-0">Online Admission Registrants</h4>
        </div>
        <!-- Online Applicants Table -->
        <div id="online-applicants" class="col-md-12 mt-4">
            <table class="table table-bordered table-hover">
                <thead class="thead-light">
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Image</th>
                        <th scope="col">Name</th>
                        <th scope="col">Address</th>
                        <th scope="col">Department Choice</th>
                        <th scope="col">Application Date</th>
                        <th scope="col">Actions</th>
                    </tr>
                </thead>
                <tbody class="bg-light">

                    {% for applicant in paid_students %}
                    <tr>
                        <th scope="row">{{ applicant.id }}</th>
                        <td>
                            <img src="{{ applicant.photo.url }}" width="50" height="50">
                        </td>
                        <td>{{ applicant.name }}</td>
                        <td>{{ applicant.permanent_address }}</td>
                        <td>{{ applicant.department_choice }}</td>
                        <td>{{ applicant.created }}</td>
                        <td>
                            <a href="" class="btn btn-sm btn-primary">More</a>
                            <a href="{% url 'students:admit_student' pk=applicant.id %}" class="btn btn-sm btn-success">
                                Admission
                            </a>
                            <a href="{% url 'students:update_online_registrant' pk=applicant.id %}"
                                class="btn btn-sm btn-info">
                                Update
                            </a>
                        </td>
                    </tr>
                    {% endfor %}

                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

{% block extrajs %}
<script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
{% endblock %}

students/templates/students/students_list.html
{% extends 'dashboard.html' %}

{% block dashboard-body %}

<div class="row">
  <div class="col-12">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Registration</th>
          <th scope="col">Name</th>
          <th scope="col">Department</th>
          <th scope="col">Action</th>
        </tr>
      </thead>
      <tbody>
        {% for student in students %}
        <tr>
          <th scope="row">
            <a href="{% url 'students:student_details' pk=student.id %}">
              {{ student.roll }}
          </th>
          <td>
            <a href="{% url 'students:student_details' pk=student.id %}">
              {{ student.registration_number }}</td>
          <td>
            <a href="{% url 'students:student_details' pk=student.id %}">
            <img src="{{ student.photo.url }}" class="mr-2 rounded-circle" height=24 width=24>
            {{ student.name }}
          </td>
          <td>
            <a href="{% url 'students:student_details' pk=student.id %}">
              {{ student.department.name }}
          </td>
          <td>
            <div class="btn-group" role="group" aria-label="Basic example">
              <button type="button" class="btn btn-success">
                <i class="fas fa-cogs"></i>
              </button>
              <a href="{% url 'students:update_student' pk=student.id %}" class="btn btn-secondary">
                <i class="fas fa-edit"></i>
              </a>
            </div>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

{% endblock %}

students/templates/students/unpaid_applicants.html
{% extends 'dashboard.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block extra_header %}
{% endblock %}

{% block dashboard-body %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="#">Dashboard</a></li>
        <li class="breadcrumb-item">
            <a href="{% url 'students:students_dashboard_index' %}">Students</a>
        </li>
        <li class="breadcrumb-item active" aria-current="page">Unpaid Applicants</li>
    </ol>
</nav>

<!-- Online Applicants Table Row -->
<div class="container-fluid">
    <div class="row">
        <div class="col-12 pl-0">
            <h4 class="ml-0">Unpaid Registrants</h4>
        </div>
        <!-- Online Applicants Table -->
        <div id="online-applicants" class="col-md-12 mt-4">
            <table class="table table-bordered table-hover">
                <thead class="thead-light">
                    <tr>
                        <th scope="col">SYL</th>
                        <th scope="col">Image</th>
                        <th scope="col">Name</th>
                        <th scope="col">Contact</th>
                        <th scope="col">Department Choice</th>
                        <th scope="col">Application Date</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody class="bg-light">
                
                    {% for applicant in unpaid_applicants %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>
                            <img src="{{ applicant.photo.url }}" width="50" height="50">
                        </td>
                        <td>
                            <a href="{% url 'students:update_online_registrant' pk=applicant.id %}" 
                            class="text-dark">
                                {{ applicant.name }}
                            </a>
                        </td>
                        <td>
                            <a href="{% url 'students:update_online_registrant' pk=applicant.id %}" 
                            class="text-dark">
                                {{ applicant.mobile_number }}
                            </a>
                        </td>
                        <td>
                            <a href="{% url 'students:update_online_registrant' pk=applicant.id %}" 
                            class="text-dark">
                                {{ applicant.department_choice }}
                            </a>
                        </td>
                        <td>
                            <a href="{% url 'students:update_online_registrant' pk=applicant.id %}" 
                            class="text-dark">
                                {{ applicant.created }}
                            </a>
                        </td>
                        <td>
                            <form action="" method="post" class="mark-paid-form">
                                {% csrf_token %}
                                <input type="hidden" name="registrant_id" value="{{ applicant.pk }}">
                                <button type="submit" class="btn btn-sm mark-paid-btn btn-dark mb-1 btn-block">
                                    <span class="mark-paid-text">Mark as paid</span>
                                </button>
                            </form>
                            <a href="{% url 'students:admit_student' pk=applicant.pk %}" 
                            class="btn btn-sm btn-primary d-block">
                                Admit
                            </a>
                        </td>
                    </tr>
                    {% endfor %}
                    
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

{% block extrajs %}
    <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <script>
        const forms = document.querySelectorAll('.mark-paid-form');
        forms.forEach(function(element){
            element.addEventListener('submit', function(event){
                event.preventDefault();
                const serializedData = $(this).serialize();
                changePayStatus(element, serializedData)
            });
        });

        function changePayStatus(element, data){
            const url = "{% url 'students:mark_as_paid_or_unpaid' %}";
            $.ajax({
                type: 'POST',
                url: url,
                data: data,
                success: function(response) {
                    if (response.data) {
                        element.querySelector('.mark-paid-text').innerHTML = '<b>PAID</b>'
                    } else {
                        element.querySelector('.mark-paid-text').innerHTML = '<b>Mark as paid</b>'
                    }
                },
                error: function(error){
                    console.log(error);
                }
            });
        }

    </script>
{% endblock %}