accounts/urls.py
from django.urls import path, include
from . import views


app_name = 'account'

urlpatterns = [
    path('', views.profile_complete, name='profile_complete'),
    path('auth/', include('django.contrib.auth.urls')),
    # register path is archived since we're using allauth'
    # path('register/', views.register, name='register'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('groups/', views.GroupListView.as_view(), name='groups'),
    path('user-requests/', views.user_requests_list, name='user_requests'),
    path('permission-error/', views.permission_error, name='permission_error'),
    path('approval/<int:pk>/<int:approved>',
         views.user_approval, name='user_approval'),
    path('modify-and-approve/<int:pk>/',
        views.user_approval_with_modification,
        name='approval_with_modification'
    ),
    path('user/<int:pk>/change', views.UserUpdateView.as_view(), name='user_change'),
    path('api/upload-profile-picture', views.profile_picture_upload,
        name='profile_picture_upload'
    ),
]

articles/urls.py
from django.urls import path

from . import views
from .dashboard_views import dashboard_views

app_name = 'articles'

urlpatterns = [
    path('',
        views.ArticleList.as_view(),
        name='home'
    ),
    path('all/', 
        views.AllArticles.as_view(), 
        name='all_articles'
    ),
    path('manage/', dashboard_views.dashboard_manage_article,
        name='dashboard_manage'
    ),
    path('manage/subscribers/', 
        dashboard_views.SubscribersManageView.as_view(),
        name='subscribers'
    ),
    path('dashboard/delete/<int:pk>/', 
        dashboard_views.dashboard_article_delete, 
        name='dashboard_article_delete'
    ),
    path('dashboard/new/',
         dashboard_views.dashboard_article_publish,
        name='dashboard_article_publish'
    ),
    path('dashboard/draft/<int:pk>/', 
        dashboard_views.dashboard_article_draft,
        name='dashboard_article_draft'
    ),
    path('dashboard/publish/article/',
         views.ArticleCreateFromDashboard.as_view(),
        name='publish_article_from_dashboard'
    ),
    path('new/',
        views.ArticleCreate.as_view(),
        name='create'
    ),
    path('newsletter/',
        views.newsletter,
        name='newsletter'
    ),
    path('author/<str:slug>/',
        views.AuthorProfile.as_view(),
        name='author_profile'
    ),
    path('<slug:slug>/update/',
        views.ArticleUpdate.as_view(),
        name='update'
    ),
    path('<slug:slug>/like/',
        views.ArticleLike.as_view(),
        name='like'
    ),
    path('<slug:slug>/',
        views.ArticleDetail.as_view(),
        name='detail'
    ),
    path('<slug:slug>/articles/',
        views.CategoryArticles.as_view(),
        name='category_articles'
    ),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

from institute.models import InstituteProfile
from accounts.views import dashboard

try:
    institute = InstituteProfile.objects.get(active=True)
    admin.site.site_header = institute.site_header
    admin.site.site_title = institute.site_title
    admin.site.index_title = institute.index_title
except:
    admin.site.site_header = 'Django Administration'
    admin.site.site_title = 'Django Site Admin'
    admin.site.index_title = 'Django Administration'

DJANGO_ADMIN_URL = settings.DJANGO_ADMIN_URL + '/'
urlpatterns = [
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path(DJANGO_ADMIN_URL, admin.site.urls),
    path('', include('pages.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('dashboard/', dashboard, name='index_view'),
    path('accounts/', include('allauth.urls')),
    path('blog/', include('articles.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('account/', include('accounts.urls')),
    path('academics/', include('academics.urls')),
    path('notices/', include('notices.site_urls')),
    path('notices/dashboard/', include('notices.dashboard_urls')),
    path('students/', include('students.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('teachers/', include('teachers.urls')),
    path('result/', include('result.urls')),
    path('institute/', include('institute.urls')),
    path(
        'password-reset/',
        auth_views.PasswordResetView.as_view(
            template_name='account/password/password_reset.html'
        ),
        name="password_reset",
    ),
    path(
        'password_reset/done/',
        auth_views.PasswordResetDoneView.as_view(
            template_name='account/password/password_reset_done.html'
        ),
        name="password_reset_done",
    ),
    path(
        'password-reset-confirm/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='account/password/password_reset_confirm.html'
        ),
        name='password_reset_confirm',
    ),
    path(
        'password-reset-complete/',
        auth_views.PasswordResetCompleteView.as_view(
            template_name='account/password/password-reset-complete.html'
        ),
        name='password_reset_complete'
    ),
    path('dashboard/payments/', include('payments.urls')),
    # API URLS
    path('api/', include('articles.api.routes')),
    path('upload/', include('django_file_form.urls')),
]

urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)
urlpatterns += static(
    settings.STATIC_URL,
    document_root=settings.STATIC_ROOT
)

if "debug_toolbar" in settings.INSTALLED_APPS:
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls))
    ] + urlpatterns

pages/urls.py
from django.urls import path
from pages.payment_views.sslpay import online_admission_sslpayment
from . import views

app_name = 'pages'
urlpatterns = [
     path('', views.index, name='landing'),
     path('admission/', views.online_admission, name='online_admission'),
     path('admission/payment/<int:pk>/', views.online_admission_payment,
          name='online_admission_payment'
     ),
     path('admission/sslpayment/<int:pk>/', online_admission_sslpayment,
          name='online_admission_sslpayment'
     ),
     path('admission/paynow/<int:pk>/', views.payment,
          name='payment'
     ),
     path('userguide/', views.user_guide_view,
          name='userguide'
     ),
]

articles/forms.py
from tinymce.widgets import TinyMCE
from mptt.forms import TreeNodeMultipleChoiceField
from django import forms
# from django.contrib.flatpages.models import FlatPage
from .models import Article, Category, Comment


class ArticleForm(forms.ModelForm):
    category = TreeNodeMultipleChoiceField(
        widget=forms.CheckboxSelectMultiple,
        queryset=Category.objects.filter(children=None),
    )
    content = forms.CharField(widget=TinyMCE(attrs={'cols': 80, 'rows': 30}))

    class Meta:
        model = Article
        fields = ['title', 'content', 'featured_image',]


class ArticleUpdateForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'content', 'featured_image',]


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content', ]

articles/api/routes.py
from rest_framework import routers
from django.urls import path, include
from .views import ArticleViewSet


router = routers.DefaultRouter()
router.register(r'articles', ArticleViewSet)

urlpatterns = [
    path('', include(router.urls)),
]

articles/api/views.py
from rest_framework import viewsets
from .serializers import ArticleSerializer
from articles.models import Article


class ArticleViewSet(viewsets.ModelViewSet):
    queryset = Article.objects.all()
    serializer_class = ArticleSerializer

articles/views.py
from braces.views import LoginRequiredMixin

from itertools import chain

from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views import View
from django.views.generic import (
    ListView, DetailView,
    CreateView, UpdateView,
    TemplateView
)

from accounts.models import User
from accounts.forms import (
    CommonUserProfileForm, 
    UserProfileSocialLinksFormSet,
)
from .models import Article, Like, Category, Newsletter
from .mixins import AuthorArticleEditMixin
from .forms import ArticleForm, ArticleUpdateForm, CommentForm
from .utils import subscribe
from articles.tasks import send_latest_article
from permission_handlers.administrative import user_is_teacher_or_administrative


class AllArticles(ListView):
    model = Article
    queryset = Article.published.all()
    context_object_name = 'articles'
    template_name = 'articles/all_articles.html'
    paginate_by = 10


class ArticleList(ListView):
    """
    Returns a list of published articles.
    """
    model = Article
    queryset = Article.published.all()
    context_object_name = 'articles'
    paginate_by = 10
    # Legacy theme
    # template_name = 'articles/articles.html'
    # Tailwind + UX Abu Ahmad's Theme
    template_name = 'articles/tailwind-theme/list_tw.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        last_article = Article.published.filter(status='published'
            ).order_by('-created').first()
        latest_featured_article = Article.published.filter(
            is_featured=True
        ).first()
        try:
            # fetch four highlisted/most-reached articles.
            highlighted_n_most_reached_articles = Article.published.filter(
                force_highlighted=True
            ).order_by(
                '-created')[:4]
        except IndexError:
            highlighted_n_most_reached_articles = Article.published.order_by(
                '-created')

        try:
            last_three_articles = Article.published.order_by('-created')[:3]
        except IndexError:
            last_three_articles = Article.published.order_by('-created')
        
        category_articles = Category.get_article_for_category()

        context['last_article'] = last_article
        context['last_three_articles'] = last_three_articles
        context['latest_featured_article'] = latest_featured_article
        context['category_articles'] = category_articles
        context['highlights'] = highlighted_n_most_reached_articles
        return context

    def get_queryset(self):
        qs = Article.published.select_related('author').select_related().all()
        return qs


class CategoryArticles(ListView):
    context_object_name = 'articles'
    template_name = 'articles/category_articles.html'

    def get_queryset(self):
        slug = self.kwargs.get('slug')
        category = Category.objects.get(slug=slug)
        articles = category.article_set.filter(status='published')
        return articles
    
    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        slug = self.kwargs.get('slug')
        category = Category.objects.get(slug=slug)
        ctx['category'] = category
        return ctx


class ArticleDetail(DetailView):
    model = Article
    # Legacy theme
    # template_name = 'articles/detail.html'
    # Tailwind+UX Abu Ahmad's Theme
    template_name = 'articles/tailwind-theme/detail_tw.html'

    def get_object(self, qs=None):
        obj = super().get_object(queryset=qs)
        # If user is not the author of article
        if obj.status == 'draft' and obj.author != self.request.user:
            raise Http404()
        return obj

    def get_context_data(self, **kwargs):
        obj = super().get_object()
        context = super().get_context_data(**kwargs)
        likes = Like.objects.filter(article=obj)
        context['likes'] = likes
        context['comments'] = obj.comments.filter(approved=True)
        if self.request.user.is_authenticated:
            context['user_pending_comments'] = obj.comments.filter(
                approved=False, 
                author=self.request.user
            )
        context['comment_form'] = CommentForm()
        return context

    def post(self, request, *args, **kwargs):
        ctx = {}
        article = super().get_object()
        if 'content' in request.POST:
            comment_form = CommentForm(request.POST)
            if comment_form.is_valid():
                comment_form.instance.author = request.user
                comment_form.instance.article = super().get_object()
                comment_form.save()
                return redirect(article.get_absolute_url())
            else:
                return HttpResponse('Comment Form Contains Invalid Data.')
        return redirect(article.get_absolute_url())

class ArticleCreate(
    AuthorArticleEditMixin, LoginRequiredMixin,
    UserPassesTestMixin, CreateView):
    # fields none need to set None to provide form_class
    # because it has some value in AuthorArticleEditMixin.
    fields = None
    form_class = ArticleForm

    def test_func(self):
        user =  self.request.user
        return user_is_teacher_or_administrative(user)

    def handle_no_permission(self):
        if self.request.user.is_authenticated:
            messages.add_message(self.request, 
                messages.INFO,
                "You're redirected to this page because you "
                "do not have right permission to publish articles. "
                "If you want to write articles in this portal, "
                "please communicate with authorities."
            )
            return redirect('account:profile_complete')
        return redirect('account_login')

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.save()
        # save categories for the article
        categories_ids = list(map(
            int, self.request.POST.getlist('category')
        ))
        categories = Category.objects.filter(id__in=categories_ids)
        form.instance.categories.add(*categories)
        return super().form_valid(form)


class ArticleUpdate(AuthorArticleEditMixin, UpdateView):
    fields = None
    form_class = ArticleUpdateForm


class ArticleLike(LoginRequiredMixin, View):
    def post(self, request, slug):
        user = request.user
        article = Article.objects.get(slug=slug)
        Like.objects.create(user=user, article=article)
        return redirect(article.get_absolute_url())


class AuthorProfile(DetailView):
    context_object_name = 'author'
    model = User
    template_name = 'articles/author_profile.html'
    
    def get_slug_field(self):
        return 'username'
    
    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        try:
            if self.request.user.is_authenticated:
                profile = self.request.user.profile
                profile_edit_form = CommonUserProfileForm(
                    instance=profile
                )
                ctx['profile_edit_form'] = profile_edit_form
                formset = UserProfileSocialLinksFormSet(
                    instance=profile
                )
                ctx['social_links_form'] = formset
        except User.profile.RelatedObjectDoesNotExist:
            ctx['profile_not_found'] = 'We did not find any profile for you, \
                please contact with authorities.'
        return ctx
    
    def post(self, request, *args, **kwargs):
        profile_form = CommonUserProfileForm(
            request.POST,
            request.FILES,
            instance=self.request.user.profile
        )
        social_formset = UserProfileSocialLinksFormSet(
            request.POST, instance=self.request.user.profile
        )
        if profile_form.is_valid():
            profile_form.save()

            if social_formset.is_valid():
                social_formset.save()
                messages.add_message(
                    request, messages.SUCCESS,
                    'Your profile has been saved successfully.'
                )
                return redirect(
                    self.request.user.get_author_url()
                )
            else:
                messages.add_message(
                    request, messages.INFO,
                    'Your profile has been saved without updating social links.'
                )
                return redirect(
                    self.request.user.get_author_url()
                )
        else:
            messages.add_message(
                request, messages.SUCCESS,
                'Please provide valid values according to the form.'
            )
            return redirect(self.request.user.get_author_url())


class ArticleCreateFromDashboard(LoginRequiredMixin,
    UserPassesTestMixin, CreateView):
    # fields none need to set None to provide form_class
    # because it has some value in AuthorArticleEditMixin.
    fields = None
    form_class = ArticleForm
    template_name = 'articles/dashboard/publish.html'

    def test_func(self):
        user =  self.request.user
        return user_is_teacher_or_administrative(user)

    def handle_no_permission(self):
        if self.request.user.is_authenticated:
            messages.add_message(self.request, 
                messages.INFO,
                "You're redirected to this page because you "
                "do not have right permission to publish articles. "
                "If you want to write articles in this portal, "
                "please communicate with authorities."
            )
            return redirect('account:profile_complete')

articles/templates/articles/all_articles.html
{% extends 'articles/base.html' %}


{% block content %}
<!-- Articles Bottom-section -->
<div class="container">
    <div class="row p-4">
      {% for article in articles %}
        <div class="col-sm-12 col-md-3 mb-5">
          <a href="{{ article.get_absolute_url }}">
            <div class="article-card rounded">
              <img src="{{article.featured_image.url}}" alt="" class="rounded article-preview-image">
              <div class="article-content">
                <small class="category-name">
                    <a href="{{ article.categories.first.get_absolute_url }}">
			            {{ article.categories.first }}
		            </a>
                </small>
                <p class="my-1">
                  <b>
                    <a href="{{ article.get_absolute_url }}">
                      {{ article.title }}
                    </a>
                  </b>
                </p>
                <div class="metadata d-flex justify-content-between pr-4">
                  <small class="fsm muted mr-3">{{ article.created }}</small>
                  <!-- <small class="fsm muted">1500 VIEWS</small> -->
                </div>
              </div>
            </div>
          </a>
        </div>
      {% endfor %}
    </div>
    <div class="row">
      <div class="col-md-12 d-flex justify-content-center">
        <!-- start pagination -->
        <nav aria-label="Page navigation example">
          <ul class="pagination">
            {% if page_obj.has_previous %}
              <li class="page-item">
                <a class="page-link" href="?page=1">&laquo; first</a>
              </li>
              <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                  prev
                </a>
              </li>
            {% endif %}

            {% for page in page_obj.paginator.page_range %}
              {% if page_obj.number == page %}
                <li class="page-item active">
                  <a class="page-link" href="?page={{ page }}">
                    {{ page }}
                  </a>
                </li>
              {% else %}
                <li class="page-item">
                  <a class="page-link" href="?page={{ page }}">
                    {{ page }}
                  </a>
                </li>
              {% endif %}
            {% endfor %}
            
            {% if page_obj.has_next %}
              <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                  next
                </a>
              </li>
              <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
                  last &raquo;
                </a>
              </li>
            {% endif %}
          </ul>
        </nav>
        <!-- end of pagination -->
      </div>
    </div>
</div>
{% endblock %}

articles/templates/articles/article_form.html
{% extends "articles/base.html" %}

{% load i18n %}
{% load crispy_forms_tags %}

{% block head_title %}
  {% if object %}
    {% trans "Update Article" %}
  {% else %}
    {% trans "Publish new article" %}
  {% endif %}
{% endblock %}

{% block content %}
  <!-- Page Header -->
  <header class="masthead" 
   {% if object.featured_image %}
   style="background-image: linear-gradient(rgba(0, 0, 0, 0.6), rgba(0, 0, 0, 0.6)),
           url('{{ object.featured_image.url }}')"
   {% else %}
     style="background-image: url('articles/img/post-bg.jpg')"
   {% endif %}>
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="post-heading">
            {% if object %}
              <h4>{% trans "Update Article" %}</h4>
              <h1>{{ object.title }}</h1>
            {% else %}
              <h1>{% trans "Publish new article" %}</h1>
            {% endif %}
            <h2 class="subheading">Keep your article clear, understandable and
            informative.</h2>
          </div>
        </div>
      </div>
    </div>
  </header>

  {# Actual form container #}
  <div class="container pt-3 article-form">
    <div class="row justify-content-center">
      <div class="col-md-10">
        <div class="d-flex">
          <a href="{% url 'articles:home' %}" class="text-dark d-block mr-2 mb-5" title="Back to home">
            <i class="fas fa-arrow-alt-circle-left fa-2x"></i>
          </a>
          <a href="{% url 'articles:create' %}" class="text-dark d-block mb-5" title="Create New Article">
            <i class="far fa-plus-square fa-2x"></i>
          </a>
        </div>
        <form class="" method="POST" action="." enctype="multipart/form-data">
          {% csrf_token %}
          {{ form.media }}
          {{ form|crispy }}
          <button class="primaryAction btn btn-primary float-right" type="submit">{% trans "Post" %}</button>
          <a href="{% url 'articles:home' %}" class="btn btn-dark float-right">
            <i class="far fa-arrow-alt-circle-left"></i> Back
          </a>
        </form>
      </div>
    </div>
  </div>


  <!-- Footer -->

  <!-- Footer -->
  <div class="bg-dark mt-5">
    {% include 'articles/inc/_footer.html' %}
  </div>
{% endblock %}

articles/templates/articles/base.html
{% load static i18n %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}{{ request_institute.site_title }} | Blog{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Analytics -->
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-QQ3GYTDRV1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-QQ3GYTDRV1');
    </script>
    
    {% block meta_tags %}{% endblock %}

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    <link rel="icon" 
      href="{% if request_institute.site_favicon %}{{request_institute.site_favicon.url}}{% else %}{% static 'articles/images/favicons/favicon.ico' %}{% endif %}">
    <!-- Latest compiled and minified Bootstrap CSS -->
    <link href="{% static 'articles/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Your stuff: Third-party CSS libraries go here -->
    <!-- Custom fonts for this template -->
    <link href="{% static 'articles/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <!-- This file stores project-specific CSS -->
    <link href="{% static 'articles/css/clean-blog.css' %}" rel="stylesheet">
    <link href="{% static 'articles/css/project.css' %}" rel="stylesheet">
    {% block css %} {% endblock %}
  </head>

  <body>

    <div class="">
      <!-- Navigation -->
      <nav class="navbar bg-dark navbar-dark fixed-top"
       id="mainNav">
        <div class="container">
          <a class="navbar-brand p-0" href="{% url 'articles:home' %}">
            <img src="{{ request_institute.logo.url }}" 
              alt="{{ request_institute.site_title }}"
              width="" height="50">
          </a>
          <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            topics
            <i class="fas fa-bars"></i>
          </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav align-items-end">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'articles:home' %}">Home</a>
              </li>
              
              <li class="nav-item">
                <a class="nav-link" href="{% url 'articles:all_articles' %}">
                  Articles
                </a>
              </li>

              <!-- Dynamic Navigation -->
              {% include 'articles/inc/_registered_navlinks.html' %}

              {% if request.user.is_authenticated %}
                <li class="nav-item">
                  {# URL provided by django-allauth/account/urls.py #}
                  <a class="nav-link" 
                    href="{% url 'articles:author_profile' slug=user.username %}">
                    {% trans "My Profile" %}
                  </a>
                </li>
                <li class="nav-item">
                  {# URL provided by django-allauth/account/urls.py #}
                  <a class="nav-link" 
                    href="{% url 'account_logout' %}">
                    {% trans "Logout" %}
                  </a>
                </li>
              {% else %}
                <li class="nav-item">
                  {# URL provided by django-allauth/account/urls.py #}
                  <a class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
                </li>
                <li class="nav-item">
                  {# URL provided by django-allauth/account/urls.py #}
                  <a class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
                </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>

    </div>

    <div class="mt-for-nav">

      <!-- {% if messages %}
          {% for message in messages %}
              <div style="position: relative; top: 30px;" class="alert {% if message.tags %}{{ message.tags }}{% endif %}">{{ message }}<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>
          {% endfor %}
      {% endif %} -->

      {% block content %}

      {% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script> -->
      <!-- Bootstrap core JavaScript -->
      <script src="{% static 'articles/vendor/jquery/jquery.min.js' %}"></script>
      <script src="{% static 'articles/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->


      <!-- place project specific Javascript in this file -->
      <script src="{% static 'articles/js/blog.js' %}"></script>
      <script src="{% static 'articles/js/project.js' %}"></script>
      <script>
      (function(){
        const windowHeight = window.innerHeight;
        const documentHeight = document.body.offsetHeight;
        const siteNav = document.querySelector('.navbar');
        // console.log(`wh: ${windowHeight}, dh: ${documentHeight}`);

        if (documentHeight <= windowHeight) {
          // console.log('content is not large enough');
          siteNav.classList.add('navbar-dark');
          siteNav.classList.add('bg-dark');
        } else {
          // console.log('content is large enough');
          siteNav.classList.add('navbar-inverse');
        }
      })();
    </script>
    {% block extra_js %}{% endblock %}
    {% endblock javascript %}
  </body>
</html>